title: Data Collection/Annotations and Inferences with LLMs in Social Sciences
description: Materials for a one-day workshop on LLM data collection/annotation and inferences
theme: jekyll-theme-minimal
github:
    is_project_page: false
